services:

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - OPENVPN_CUSTOM_CONFIG=${OPENVPN_CUSTOM_CONFIG}
      - TZ=${TZ}
    volumes:
      - ./appdata/gluetun:/gluetun
    ports:
      - 8080:8080
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}    
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ./appdata/qbittorrent:/config
      - ./downloads:/downloads
    restart: unless-stopped
    
  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    networks:
      - media
    environment:
      - PUID=${PUID}    
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./appdata/prowlarr:/config
    ports:
      - 19696:9696
    restart: unless-stopped
  
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    networks:
      - media
    environment:
      - PUID=${PUID}    
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./appdata/radarr:/config
      - ./movies:/movies
      - ./downloads:/downloads
    ports:
      - 17878:7878
    restart: unless-stopped
  
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    networks:
      - media
    environment:
      - PUID=${PUID}    
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./appdata/sonarr:/config
      - ./downloads:/downloads
      - ./series:/series
    ports:
      - 18989:8989
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    networks:
      - media
    environment:
      - PUID=${PUID}    
      - PGID=${PGID}
      - TZ=Europe/Paris
    volumes:
      - ./appdata/bazarr:/config
      - ./movies:/movies
      - ./series:/series
    ports:
      - 16767:6767
    restart: unless-stopped


  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    networks:
      - media
    environment:
      - TZ=${TZ}
    volumes:
      - ./appdata/jellyfin:/config
      - ./cache/jellyfin:/cache
      - ./movies:/movies
      - ./series:/series
    ports:
      - 18096:8096
    restart: unless-stopped

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    networks:
      - media
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}    
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${URL}        
      - SUBDOMAINS=${SUBDOMAINS}
      - VALIDATION=${VALIDATION}
      - DUCKDNSTOKEN=${DUCKDNS_TOKEN}
      - EMAIL=${EMAIL}
    volumes:
      - ./appdata/swag:/config
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped

  duckdns:
    image: lscr.io/linuxserver/duckdns
    container_name: duckdns
    networks:
      - media
    environment:
      - SUBDOMAINS=${URL}
      - TOKEN=${DUCKDNS_TOKEN}
      - TZ=${TZ}
    volumes:
      - ./appdata/duckdns:/config
    restart: unless-stopped

networks:
  media:
    driver: bridge

